[build]
  command = "pnpm run build"
  publish = "dist"

[dev]
  framework = "astro"
  command = "pnpm run dev"
  autoLaunch = false

[[plugins]]
package = "netlify-plugin-minify-html"
  [plugins.inputs.minifierOptions]
    collapseWhitespace = true
    minifyJS = true
    processScripts = ["module"]

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"