[build]
  command = "pnpm run build"
  publish = "dist"

[dev]
  framework = "astro"
  command = "pnpm run dev"
  autoLaunch = false

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"